# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0958343501c78d59651f26d9027723cde5595c2c251fd3f0d2fafeaa3a5f7219534b10ac26c006b8e9546aa99eb77c7fc9d6bb1833bf13fb8be74cc10a6b1748

test:
  secret_key_base: 37def8fbd382e49b4f812fd3e3bc8615dd20c9ce84a2f45846ffb97a99251a13083b442a11c5bb64976356449d74352c65548bb831df293cb95defdb7469c26f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
